// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeTMpW2Tpn6gkMaQEFdDyjdh_As-cefrI',
    appId: '1:91321942151:web:6b9dcd29e693ceb6f83822',
    messagingSenderId: '91321942151',
    projectId: 'my-chat-e1795',
    authDomain: 'my-chat-e1795.firebaseapp.com',
    storageBucket: 'my-chat-e1795.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG6aXe5usI_5BtXBbc9PNJWZ6Y8RBXaHY',
    appId: '1:91321942151:android:0ff8a4ffb12599b0f83822',
    messagingSenderId: '91321942151',
    projectId: 'my-chat-e1795',
    storageBucket: 'my-chat-e1795.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6aWUGgGMenMBqvc2eyMNFavaLtr7c4SQ',
    appId: '1:91321942151:ios:37a1ef6839a686f4f83822',
    messagingSenderId: '91321942151',
    projectId: 'my-chat-e1795',
    storageBucket: 'my-chat-e1795.appspot.com',
    androidClientId: '91321942151-8mnc98qq62oual8urtogq2bk9klc0t2s.apps.googleusercontent.com',
    iosClientId: '91321942151-o3gq5m54eubu2oal57pem4vtv32ld24j.apps.googleusercontent.com',
    iosBundleId: 'com.gmail.mukatdisovilyas.myChat',
  );
}
